//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cohen451Final.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ReturnProducts", ReplyAction="http://tempuri.org/IProductService/ReturnProductsResponse")]
        ProductService.ProductSer[] ReturnProducts(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ReturnProducts", ReplyAction="http://tempuri.org/IProductService/ReturnProductsResponse")]
        System.Threading.Tasks.Task<ProductService.ProductSer[]> ReturnProductsAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : Cohen451Final.ServiceReference1.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<Cohen451Final.ServiceReference1.IProductService>, Cohen451Final.ServiceReference1.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductService.ProductSer[] ReturnProducts(string id) {
            return base.Channel.ReturnProducts(id);
        }
        
        public System.Threading.Tasks.Task<ProductService.ProductSer[]> ReturnProductsAsync(string id) {
            return base.Channel.ReturnProductsAsync(id);
        }
    }
}
